### ISSUE TITLE
Write documentation

### ISSUE THREAD

**Issue by genderev** [genderev/code-sharer#13]
Code Sharer is a website that allows programmers to share colorful snippets of code 🎨

What do you think should be in the documentation? It's up to you. Try the app [here](https://codesharer.netlify.app) and document your experience.

[This article](https://dev.to/dhintz89/contributing-to-open-source-50dk) will help you make a pull request!

**Comment by rohan2734** [comment]
hi i would like to work on this issue.

**Comment by genderev** [comment]
@rohan2734 Awesome! It's great to see you 🎉 Thanks for contributing!

I assigned this issue to you.

If you need any help, you can always comment here. There are no bad questions!

**Comment by rohan2734** [comment]
> @rohan2734 Awesome! It's great to see you 🎉 Thanks for contributing!
> 
> I assigned this issue to you.
> 
> If you need any help, you can always comment here. There are no bad questions!

thanks i will create a PR on October 1.

**Comment by rohan2734** [comment]
hey @genderev  ,the documentation is ready, i will put a pull request on october 1.

**Comment by rohan2734** [comment]
@genderev   , hey you can check this repo , i have done the task, look at rohan2734 branch, https://github.com/rohan2734/code-sharer, please tell me if you want to add anything.

**Comment by genderev** [comment]
> @genderev , hey you can check this repo , i have done the task, look at rohan2734 branch, https://github.com/rohan2734/code-sharer, please tell me if you want to add anything.

Hi @rohan2734! Where is the documentation?

**Comment by rohan2734** [comment]
@genderev  in the readme file.

**Comment by rohan2734** [comment]
@genderev when i searched in the net, i got the information that we can write documentaiton in README.md ,so i have done that there

**Comment by genderev** [comment]
Hi @rohan2734, your pull request does not include any documentation.

**Comment by rohan2734** [comment]
- @genderev ok, so i might be wrong, i did it like this since i got the results from one of the search apperances.
- so how exactly do you want me to do documentation.?
- you can provide me the links for it

**Comment by genderev** [comment]
Hi @rohan2734, I don't know how to help. I think this issue is too advanced for beginners, which I didn't realize at first. I hope you get pull requests somewhere else!

**Comment by rohan2734** [comment]
@genderev no i am not a beginner, i am intermediate, you can help me in writing the documentation. I am ready to learn and do the task as soon as possible.
