### ISSUE TITLE
Edit the README for this repo

### ISSUE THREAD

**Issue by genderev** [genderev/code-sharer#14]
`Code Sharer is a website that allows programmers to share colorful snippets of code 🎨.`
`It's basically Github Gists, but with color.`

Is that a good README? You can make it better. Make a pull request! 

1. Fork this repository 🍴
2. Create a branch: `git checkout -b .`
3. Make your changes and commit them: `git commit -m ' ' `
4. Push to the original branch: `git push origin / `
5. Create the pull request ✨ you're done!

Is that confusing? [This article](https://dev.to/dhintz89/contributing-to-open-source-50dk) explains it well.

Note: [This repo](https://github.com/noffle/art-of-readme) explains what makes for a good README.

**Comment by Abhicoder03** [comment]
Hey, I want to work on this.

**Comment by malhotramanik** [comment]
@genderev submitted PR
Hopefully, I have done it right as I am new to open source

**Comment by genderev** [comment]
People were not improving the README, so I'm going to close this.
