### ISSUE TITLE
"Copy Embed Link" not copying anything

### ISSUE THREAD

**Issue by AdityaNikhil** [genderev/code-sharer#15]
I tried using the app just now and while am trying to click the **Copy Embed Link** . It's not copying the link to clipboard. Also I inspected on the button and this was the error that's occuring while am trying to click,

![image](https://user-images.githubusercontent.com/30192967/94356787-f2efa300-00af-11eb-8141-a432c54d3140.png)

**Comment by genderev** [comment]
Hi! Thank you so much for making this issue!

The way `js/index.js` functioned was to only generate a link once the user edited the text field.

tl;dr copyText was not defined, but I changed that. How is it now?

**Comment by AdityaNikhil** [comment]
Hey there,
Stilll it's not copying any link to the clipboard.

**Comment by genderev** [comment]
Can you show me your console again?

**Comment by AdityaNikhil** [comment]
![Capture](https://user-images.githubusercontent.com/30192967/94366946-f9eed380-00f8-11eb-9448-a58045252730.JPG)
Here you go!

**Comment by genderev** [comment]
Hi, did you refresh the page and clear the cache? You're viewing an old version of the website.

I removed the reference to the `manifest.json` after seeing your errors but the fact that you're seeing the same errors means the site never updated for you.

**Comment by AdityaNikhil** [comment]
Oh yeah my bad, after clearing the cache. I am able to copy the link.
Anyway I have just one another doubt. I want to embed this colorful code in my medium articles. When i try to paste the copied embed link, I cannot see the code. (Maybe medium won't accept other embed code links except github gists)
![image](https://user-images.githubusercontent.com/30192967/94367310-75518480-00fb-11eb-82f8-dbe673286048.png)

**Comment by genderev** [comment]
Thank you so much for trying Code Sharer! It’s actually not...ready to be used yet!

I should have explained in the README that this project isn’t done. I’m sorry for the confusion.

Thank you so much for trying it out! I wish I had completed everything so that you would be able to use it on Medium!

**Comment by AdityaNikhil** [comment]
No need to be sorry, it's really one of the coolest ideas and am glad to be a small part of it. Anyway, I'll try to check if there's anyway to make use of it in medium and make PRs.
