### ISSUE TITLE
Add browser logo to webpage ⭐️

### ISSUE THREAD

**Issue by genderev** [genderev/code-sharer#18]
A browser logo is known as a favicon. The favicon is the logo you see in your browser tab on your desktop next to the name of a website.

[This](https://dev.to/rnagarajan96/answer-how-to-add-a-browser-tab-icon-favicon-for-a-website-2730) explains how to add a favicon.

Right now you're in the repository for Code Sharer. Code Sharer is a website that allows programmers to share colorful snippets of code 🎨

Code Sharer doesn't have a favicon! Can you add one?

**Comment by rishavjaiss** [comment]
Yes! I can do this!

**Comment by AdityaNikhil** [comment]
Please check the pull request, added bowser logo successfully!

**Comment by rishavjaiss** [comment]
@genderev I think on this open platform each one of us should get the chance. If I replied to issue first, I should be given the chance rather than somebody not yet assigned. You should assign somebody.

**Comment by genderev** [comment]
No worries! There's two browser logos to add.

One is called: `favicon.ico`

The other is called: `apple-touch-icon`

Can you add the `apple-touch-icon`, @rishavjaiss ? This is how you do it:

- Create a file called 'apple-touch-icon.png' with the logo
- Put this file in the `images` folder

**Comment by rishavjaiss** [comment]
Okay. I'll do for the apple-touch-icon. Should I make PR before 1st and you merge it during hacktoberfest? Thanks

**Comment by genderev** [comment]
All done! Woohoo!
