### ISSUE TITLE
Embed code snippets in Medium + dev.to articles

### ISSUE THREAD

**Issue by genderev** [genderev/code-sharer#20]
Code Sharer creates colorful code snippets 🎨 but you can't embed them in your articles yet. I don't know how.

Here's what I know: 

- embedded code snippets are iframes
- to embed code snippets on dev.to, you need to convert your iframe to a Liquid tag

Here's what I don't know:

- how to create the iframe
- how to create the Liquid tag (ruby) from the iframe

This is a technical issue so don't worry too much if you don't understand, I don't either. I'm still working on this!

**Comment by AdityaNikhil** [comment]
@genderev  I request you to assign this to me.

**Comment by genderev** [comment]
@AdityaNikhil That's so awesome! It makes me happy that you want to do this.

The main question I have is: how do you convert an [iframe to a Liquid tag for dev.to](https://docs.dev.to/frontend/liquid-tags/)? The Medium side of things I understand more.

**Comment by AdityaNikhil** [comment]
Am totally new to this, am hoping if you can help me here.

**Comment by genderev** [comment]
@AdityaNikhil I'm new to this too! 

Right now, I have some new information: [this](https://github.com/forem/forem/blob/5eda086e782ef65d5fc14811de57a0efa90909ba/docs/frontend/liquid-tags.md) is the page that explains how to make Liquid tags for dev.to.

**Comment by AdityaNikhil** [comment]
@genderev Here's what i found after inspecting on a github gist in medium article,

![image](https://user-images.githubusercontent.com/30192967/94404458-ae860500-018c-11eb-82ba-153efa3feec9.png)

I guess the medium will automatically detect that the link is from github gist and it'll attach the code as it is.

So how do you think we'll integrate code-sharer with the medium?

**Comment by genderev** [comment]
Hi @AdityaNikhil! 🌟

[This](https://docs.embed.ly/docs/how-to-embed-on-medium) is how to embed code snippets on Medium - we need to become an embed.ly provider. I already filled out the form to become an embed.ly provider so we'll see how it goes.

### Overall
**Medium code snippets**: underway
**dev.to code snippets**: not figured out yet

**Comment by genderev** [comment]
__Medium__: Haven't gotten an email back from embed.ly.
__dev.to__: One of their senior software engineers volunteered to code with me on stream next Thursday! Excited to collab with their team. It might fall through, but that's the plan for now.

**Comment by AdityaNikhil** [comment]
@genderev That's great news!!!

Looking forward to see colorful codes inside dev.to one day... Wish you good luck!!!

**Comment by genderev** [comment]
@AdityaNikhil

- code stream fell through
- forem blocked my pull request
- medium never responded to me

This project is dead.
